name 'formatron_kibana'
version '0.1.1'
description 'Formatron Kibana cookbook'
maintainer 'Peter Halliday'
maintainer_email 'pghalliday@gmail.com'
source_url 'https://github.com/formatron/kibana-cookbook'
issues_url 'https://github.com/formatron/kibana-cookbook/issues'
supports 'ubuntu'
